Repository go-and-blin/go-and-blin-BE, pull requests merged in 2025-01, with the labels that each got.

#5 [Refactor] config 분리
  build.gradle
  src/main/java/com/goblin/goandblinblog/GoAndBlinBlogApplication.java
  src/main/java/com/goblin/goandblinblog/global/config/JpaAuditingConfig.java
  src/test/java/com/goblin/goandblinblog/IntegrationTestSupport.java
Labels: Refactor

#12 [Feat] 카테고리 수정 기능 구현
  src/main/java/com/goblin/goandblinblog/domain/category/controller/CategoryController.java
  src/main/java/com/goblin/goandblinblog/domain/category/controller/dto/request/CategoryCreateRequest.java
  src/main/java/com/goblin/goandblinblog/domain/category/controller/dto/request/CategoryUpdateRequest.java
  src/main/java/com/goblin/goandblinblog/domain/category/controller/port/CategoryService.java
  src/main/java/com/goblin/goandblinblog/domain/category/entity/Category.java
  src/main/java/com/goblin/goandblinblog/domain/category/repository/CategoryRepositoryImpl.java
  src/main/java/com/goblin/goandblinblog/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/goblin/goandblinblog/domain/category/service/dto/CategoryUpdateServiceRequest.java
  src/main/java/com/goblin/goandblinblog/domain/category/service/port/CategoryRepository.java
  src/main/java/com/goblin/goandblinblog/global/exception/ErrorCode.java
  src/main/java/com/goblin/goandblinblog/global/exception/GlobalExceptionHandler.java
  src/main/java/com/goblin/goandblinblog/global/exception/category/CategoryNotFoundException.java
  src/test/java/com/goblin/goandblinblog/domain/category/controller/CategoryControllerTest.java
  src/test/java/com/goblin/goandblinblog/domain/category/service/CategoryServiceTest.java
Labels: Feat

#13 [Feat] 카테고리 단일 조회 구현
  src/main/java/com/goblin/goandblinblog/domain/category/controller/CategoryController.java
  src/main/java/com/goblin/goandblinblog/domain/category/controller/dto/request/CategoryUpdateRequest.java
  src/main/java/com/goblin/goandblinblog/domain/category/controller/port/CategoryService.java
  src/main/java/com/goblin/goandblinblog/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/goblin/goandblinblog/domain/category/service/dto/request/CategoryUpdateServiceRequest.java
  src/main/java/com/goblin/goandblinblog/domain/category/service/dto/response/CategoryResponse.java
  src/test/java/com/goblin/goandblinblog/domain/category/controller/CategoryControllerTest.java
  src/test/java/com/goblin/goandblinblog/domain/category/service/CategoryServiceTest.java
Labels: Feat

#14 [Feat] 카테고리 전체 조회 기능 구현
  src/main/java/com/goblin/goandblinblog/domain/category/controller/CategoryController.java
  src/main/java/com/goblin/goandblinblog/domain/category/controller/port/CategoryService.java
  src/main/java/com/goblin/goandblinblog/domain/category/repository/CategoryJpaRepository.java
  src/main/java/com/goblin/goandblinblog/domain/category/repository/CategoryRepositoryImpl.java
  src/main/java/com/goblin/goandblinblog/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/goblin/goandblinblog/domain/category/service/dto/CategoryUpdateServiceRequest.java
  src/main/java/com/goblin/goandblinblog/domain/category/service/port/CategoryRepository.java
  src/main/java/com/goblin/goandblinblog/global/exception/ErrorCode.java
  src/main/java/com/goblin/goandblinblog/global/exception/GlobalExceptionHandler.java
  src/test/java/com/goblin/goandblinblog/domain/category/controller/CategoryControllerTest.java
  src/test/java/com/goblin/goandblinblog/domain/category/service/CategoryServiceTest.java
Labels: Feat

#15 [Feat] 로그인 기능 구현
  src/main/java/com/goblin/goandblinblog/domain/auth/controller/AuthController.java
  src/main/java/com/goblin/goandblinblog/domain/auth/controller/dto/request/AuthLoginRequest.java
  src/main/java/com/goblin/goandblinblog/domain/auth/controller/port/AuthService.java
  src/main/java/com/goblin/goandblinblog/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/goblin/goandblinblog/domain/comment/entity/Comment.java
  src/main/java/com/goblin/goandblinblog/domain/member/entity/Member.java
  src/main/java/com/goblin/goandblinblog/domain/member/repository/MemberJpaRepository.java
  src/main/java/com/goblin/goandblinblog/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/goblin/goandblinblog/domain/member/sevice/port/MemberRepository.java
  src/main/java/com/goblin/goandblinblog/domain/post/entity/Post.java
  src/main/java/com/goblin/goandblinblog/global/anootation/CurrentLoginMember.java
  src/main/java/com/goblin/goandblinblog/global/anootation/CurrentLoginMemberArgumentResolver.java
  src/main/java/com/goblin/goandblinblog/global/config/SecurityConfig.java
  src/main/java/com/goblin/goandblinblog/global/config/WebMvcConfig.java
  src/main/java/com/goblin/goandblinblog/global/domain/auth/filter/LoginFilter.java
  src/main/java/com/goblin/goandblinblog/global/domain/auth/service/CustomMemberDetailService.java
  src/main/java/com/goblin/goandblinblog/global/domain/base/BaseTimeEntity.java
  src/main/java/com/goblin/goandblinblog/global/domain/token/common/TokenExpiration.java
  src/main/java/com/goblin/goandblinblog/global/domain/token/common/TokenType.java
  src/main/java/com/goblin/goandblinblog/global/domain/token/dto/response/TokenResponse.java
  src/main/java/com/goblin/goandblinblog/global/domain/token/filter/JwtAuthenticationFilter.java
  src/main/java/com/goblin/goandblinblog/global/domain/token/handler/CustomAuthenticationFailHandler.java
  src/main/java/com/goblin/goandblinblog/global/domain/token/handler/CustomAuthorizationSuccessHandler.java
  src/main/java/com/goblin/goandblinblog/global/domain/token/provider/TokenProvider.java
  src/main/java/com/goblin/goandblinblog/global/exception/ErrorCode.java
  src/main/java/com/goblin/goandblinblog/global/exception/auth/InvalidLoginException.java
  src/main/java/com/goblin/goandblinblog/global/exception/member/MemberNotFoundException.java
  src/test/java/com/goblin/goandblinblog/global/domain/token/provider/TokenProviderTest.java
Labels: Feat

#17 [Chore] 의미 없는 공백 및 패키지 네임 수정
  src/main/java/com/goblin/goandblinblog/GoAndBlinBlogApplication.java
  src/main/java/com/goblin/goandblinblog/domain/category/controller/CategoryController.java
  src/main/java/com/goblin/goandblinblog/domain/category/controller/dto/request/CategoryCreateRequest.java
  src/main/java/com/goblin/goandblinblog/domain/category/controller/dto/request/CategoryUpdateRequest.java
  src/main/java/com/goblin/goandblinblog/domain/category/controller/port/CategoryService.java
  src/main/java/com/goblin/goandblinblog/domain/category/entity/Category.java
  src/main/java/com/goblin/goandblinblog/domain/category/entity/CategoryType.java
  src/main/java/com/goblin/goandblinblog/domain/category/repository/CategoryJpaRepository.java
  src/main/java/com/goblin/goandblinblog/domain/category/repository/CategoryRepositoryImpl.java
  src/main/java/com/goblin/goandblinblog/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/goblin/goandblinblog/domain/category/service/dto/request/CategoryCreateServiceRequest.java
  src/main/java/com/goblin/goandblinblog/domain/category/service/dto/request/CategoryUpdateServiceRequest.java
  src/main/java/com/goblin/goandblinblog/domain/category/service/dto/response/CategoryResponse.java
  src/main/java/com/goblin/goandblinblog/domain/category/service/port/CategoryRepository.java
  src/main/java/com/goblin/goandblinblog/domain/comment/controller/CommentController.java
  src/main/java/com/goblin/goandblinblog/domain/comment/controller/port/CommentService.java
  src/main/java/com/goblin/goandblinblog/domain/comment/entity/Comment.java
  src/main/java/com/goblin/goandblinblog/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/goblin/goandblinblog/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/goblin/goandblinblog/domain/comment/service/port/CommentRepository.java
  src/main/java/com/goblin/goandblinblog/domain/comment/sevice/port/CommentRepository.java
  src/main/java/com/goblin/goandblinblog/domain/image/controller/ImageController.java
  src/main/java/com/goblin/goandblinblog/domain/image/controller/port/ImageService.java
  src/main/java/com/goblin/goandblinblog/domain/image/entity/Image.java
  src/main/java/com/goblin/goandblinblog/domain/image/entity/ImageType.java
  src/main/java/com/goblin/goandblinblog/domain/image/repository/ImageRepositoryImpl.java
  src/main/java/com/goblin/goandblinblog/domain/image/service/ImageServiceImpl.java
  src/main/java/com/goblin/goandblinblog/domain/image/service/port/ImageRepository.java
  src/main/java/com/goblin/goandblinblog/domain/image/sevice/port/ImageRepository.java
  src/main/java/com/goblin/goandblinblog/domain/member/controller/MemberController.java
  src/main/java/com/goblin/goandblinblog/domain/member/controller/port/MemberService.java
  src/main/java/com/goblin/goandblinblog/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/goblin/goandblinblog/domain/member/service/MemberServiceImpl.java
  src/main/java/com/goblin/goandblinblog/domain/member/service/port/MemberRepository.java
  src/main/java/com/goblin/goandblinblog/domain/post/controller/PostController.java
  src/main/java/com/goblin/goandblinblog/domain/post/controller/port/PostService.java
  src/main/java/com/goblin/goandblinblog/domain/post/entity/Post.java
  src/main/java/com/goblin/goandblinblog/domain/post/repository/PostJpaRepository.java
  src/main/java/com/goblin/goandblinblog/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/goblin/goandblinblog/domain/post/service/PostServiceImpl.java
  src/main/java/com/goblin/goandblinblog/domain/post/service/port/PostRepository.java
  src/main/java/com/goblin/goandblinblog/domain/post/sevice/port/PostRepository.java
  src/main/java/com/goblin/goandblinblog/global/config/JpaAuditingConfig.java
  src/main/java/com/goblin/goandblinblog/global/config/QueryDslConfig.java
  src/main/java/com/goblin/goandblinblog/global/domain/auth/service/CustomMemberDetailService.java
  src/main/java/com/goblin/goandblinblog/global/domain/base/BaseTimeEntity.java
  src/main/java/com/goblin/goandblinblog/global/domain/token/common/TokenType.java
  src/main/java/com/goblin/goandblinblog/global/domain/token/dto/response/TokenResponse.java
  src/main/java/com/goblin/goandblinblog/global/exception/GoAndBlinException.java
  src/main/java/com/goblin/goandblinblog/global/exception/category/CategoryExistsException.java
  src/main/java/com/goblin/goandblinblog/global/exception/category/CategoryNotFoundException.java
  src/main/java/com/goblin/goandblinblog/global/exception/dto/ErrorResponse.java
  src/test/java/com/goblin/goandblinblog/ControllerTestSupport.java
  src/test/java/com/goblin/goandblinblog/GoAndBlinBlogApplicationTests.java
  src/test/java/com/goblin/goandblinblog/IntegrationTestSupport.java
  src/test/java/com/goblin/goandblinblog/domain/category/controller/CategoryControllerTest.java
Labels: Chore

#23 [Refactor] 카테고리 리팩토링
  src/test/java/com/goblin/goandblinblog/domain/category/controller/CategoryControllerTest.java
  src/test/java/com/goblin/goandblinblog/domain/category/service/CategoryServiceTest.java
Labels: Refactor
